In [1]:
import utils
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

%matplotlib inline

In [2]:
train_loader, test_loader = utils.mnist()

Processing...
Done!


In [3]:
batch_x, batch_y = next(iter(train_loader))
print(batch_x.shape, batch_y.shape)

torch.Size([50, 1, 28, 28]) torch.Size([50])


In [8]:
flatten_x = batch_x.view(-1, 784)
print(flatten_x.shape)

torch.Size([50, 784])


In [9]:
layer = nn.Linear(784, 10)
print([p.shape for p in layer.parameters()])
params = [p for p in layer.parameters()]
print(params[1])

[torch.Size([10, 784]), torch.Size([10])]
Parameter containing:
tensor([-0.0217, -0.0301,  0.0270,  0.0046, -0.0006, -0.0067,  0.0013, -0.0222,
         0.0238,  0.0281], requires_grad=True)


In [10]:
hidden_x = layer(flatten_x)
print(hidden_x.shape, hidden_x[0][:10])

torch.Size([50, 10]) tensor([-0.3935, -1.0760,  0.1432,  1.2647,  0.3721,  0.0855, -0.4628,  0.8970,
         1.0850, -0.0453], grad_fn=<SliceBackward>)


In [11]:
rectified = F.relu(hidden_x)
print(hidden_x[0])
print(rectified[0])

tensor([-0.3935, -1.0760,  0.1432,  1.2647,  0.3721,  0.0855, -0.4628,  0.8970,
         1.0850, -0.0453], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.1432, 1.2647, 0.3721, 0.0855, 0.0000, 0.8970, 1.0850,
        0.0000], grad_fn=<SelectBackward>)
